export const products = [
  {
    id: "menu-1",
    image: "/7.png",
    name: "Gabin Bar Vanilla",
    price: 12000,
    description: "Gabin bar vanilla yang renyah dan creamy.",
  },
  {
    id: "menu-2",
    image: "/8.png",
    name: "Gabin Bar Chocolate",
    price: 12000,
    description: "Gabin bar coklat yang lumer di mulut.",
  },
  {
    id: "menu-3",
    image: "/9.png",
    name: "Gabin Bar Matcha",
    price: 12000,
    description: "Gabin bar matcha dengan rasa earthy.",
  },
  {
    id: "menu-4",
    image: "/10.png",
    name: "Gabin Bar Strawberry",
    price: 12000,
    description: "Gabin bar strawberry yang segar.",
  },
  {
    id: "menu-5",
    image: "/13.png",
    name: "Gabin Bar Matcha Strawberry",
    price: 14000,
    description: "Kombinasi matcha dan strawberry.",
  },
  {
    id: "menu-6",
    image: "/11.png",
    name: "Gabin Bar Cookies and Cream",
    price: 14000,
    description: "Gabin bar cookies and cream.",
  },
  {
    id: "menu-7",
    image: "/12.png",
    name: "Gabin Bar manggo",
    price: 14000,
    description: "Gabin bar manggo yang manis.",
  },
  {
    id: "menu-8",
    image: "/14.png",
    name: "Gabin Bar Blueberry Choco",
    price: 14000,
    description: "Gabin bar blueberry dengan choco.",
  },
  {
    id: "menu-9",
    image: "/15.png",
    name: "Gabin Bar Mix Berry Crumble",
    price: 14000,
    description: "Gabin bar mix berry dengan crumble.",
  },
  {
    id: "menu-10",
    image: "/dobelchoco.png",
    name: "Gabin Bar Double Choco",
    price: 14000,
    description: "Gabin bar dengan rasa dobel choco.",
  },
  {
    id: "menu-11",
    image: "/roasted-da-hong-pao.png",
    name: "Roasted Milk Tea Da Hong Pao",
    price: 20000,
    description: "Minuman roasted milk tea Da Hong Pao.",
  },
  {
    id: "menu-12",
    image: "/roasted-melati.png",
    name: "Roasted Milk Tea Melati",
    price: 20000,
    description: "Minuman roasted milk tea melati.",
  },
  {
    id: "menu-13",
    image: "/thermal-bag.png",
    name: "Thermal bag + Ice Pack",
    price: 5000,
    description: "Tambahan kemasan thermal + ice pack.",
  },
];

export const product = products[0];
